import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header.jsx";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen text-zinc-100`}
      >
        <div className="relative overflow-hidden">
          <div className="relative mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8">
            <Header />
            <main className="mt-12">{children}</main>
          </div>
        </div>
        <div id="newsModal-root-content" />
      </body>
    </html>
  );
}
